config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection do
      get 'inativo'
    end
  end

  resources :curso_escolas
  resources :professores
  resources :cursos
  resources :escolas

end

app/models/aluno.rb
class Aluno < ActiveRecord::Base
  belongs_to :curso_escola
end

app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]

  # GET /alunos
  # GET /alunos.json
  def index
    @alunos = Aluno.where('ativo = ?', true)
  end
  
   def inativo
    @alunos = Aluno.where('ativo = ?', false)
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  end

  # GET /alunos/1/edit
  def edit
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)

    respond_to do |format|
      if @aluno.save
        format.html { redirect_to @aluno, notice: 'Aluno was successfully created.' }
        format.json { render :show, status: :created, location: @aluno }
      else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
    respond_to do |format|
      if @aluno.update(aluno_params)
        format.html { redirect_to @aluno, notice: 'Aluno was successfully updated.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @aluno.destroy
    respond_to do |format|
      format.html { redirect_to alunos_url, notice: 'Aluno was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :cpf, :curso_escola_id, :email, :ativo)
    end
end

app/helpers/alunos_helper.rb
module AlunosHelper
end

app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :curso_escola_id %><br>
    <%= f.select(:curso_escola_id, CursoEscola.all.collect {|i| ["#{i.curso.nome if !i.curso.nil?} #{i.professor.nome if !i.professor.nil?}", i.id]}, { prompt: "Selecione Curso" })  %>
  </div>
  <div class="field">
    <%= f.label :ativo %><br>
    <%= f.check_box :ativo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alunos/edit.html.erb
<h1>Editing Aluno</h1>

<%= render 'form' %>

<%= link_to 'Show', @aluno %> |
<%= link_to 'Back', alunos_path %>

app/views/alunos/inativo.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Curso escola</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.cpf %></td>
        <td><%= (aluno.curso_escola.curso.nome if !aluno.curso_escola.curso.nil?) if !aluno.curso_escola.nil? %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>

app/views/alunos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Alunos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cpf</th>
      <th>Curso escola</th>
      <th>Ativo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alunos.each do |aluno| %>
      <tr>
        <td><%= aluno.nome %></td>
        <td><%= aluno.cpf %></td>
        <td><%= (aluno.curso_escola.curso.nome if !aluno.curso_escola.curso.nil?) if !aluno.curso_escola.nil? %></td>
        <td><%= link_to 'Show', aluno %></td>
        <td><%= link_to 'Edit', edit_aluno_path(aluno) %></td>
        <td><%= link_to 'Destroy', aluno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Aluno', new_aluno_path %>
<%= link_to 'alunos inativos', :controller => '/alunos', :action => 'inativo' %>

app/views/alunos/new.html.erb
<h1>New Aluno</h1>

<%= render 'form' %>

<%= link_to 'Back', alunos_path %>

app/views/alunos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @aluno.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @aluno.cpf %>
</p>

<p>
  <strong>Curso escola:</strong> 
  <%= (@aluno.curso_escola.curso.nome if !@aluno.curso_escola.curso.nil?) if !@aluno.curso_escola.curso.nil? %>
</p>

<%= link_to 'Edit', edit_aluno_path(@aluno) %> |
<%= link_to 'Back', alunos_path %>