config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection do
      get 'inativo'
    end
  end

  resources :curso_escolas
  resources :professores
  resources :cursos
  resources :escolas

end

app/models/curso.rb
class Curso < ActiveRecord::Base
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url, notice: 'Curso was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:nome, :carga_horaria, :descricao)
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_form.html.erb
<%= form_for(@curso) do |f| %>
  <% if @curso.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso.errors.count, "error") %> prohibited this curso from being saved:</h2>

      <ul>
      <% @curso.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :carga_horaria %><br>
    <%= f.number_field :carga_horaria %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing Curso</h1>

<%= render 'form' %>

<%= link_to 'Show', @curso %> |
<%= link_to 'Back', cursos_path %>

app/views/cursos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Carga horaria</th>
      <th>Descricao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
      <tr>
        <td><%= curso.nome %></td>
        <td><%= curso.carga_horaria %></td>
        <td><%= curso.descricao %></td>
        <td><%= link_to 'Show', curso %></td>
        <td><%= link_to 'Edit', edit_curso_path(curso) %></td>
        <td><%= link_to 'Destroy', curso, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso', new_curso_path %>

app/views/cursos/new.html.erb
<h1>New Curso</h1>

<%= render 'form' %>

<%= link_to 'Back', cursos_path %>

app/views/cursos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @curso.nome %>
</p>

<p>
  <strong>Carga horaria:</strong>
  <%= @curso.carga_horaria %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @curso.descricao %>
</p>

<%= link_to 'Edit', edit_curso_path(@curso) %> |
<%= link_to 'Back', cursos_path %>