config/routes.rb
Rails.application.routes.draw do
  resources :alunos do
    collection do
      get 'inativo'
    end
  end

  resources :curso_escolas
  resources :professores
  resources :cursos
  resources :escolas

end

app/models/curso_escola.rb
class CursoEscola < ActiveRecord::Base
  belongs_to :escola
  belongs_to :curso
  belongs_to :professor
end

app/controllers/curso_escolas_controller.rb
class CursoEscolasController < ApplicationController
  before_action :set_curso_escola, only: [:show, :edit, :update, :destroy]

  # GET /curso_escolas
  # GET /curso_escolas.json
  def index
    @curso_escolas = CursoEscola.all
  end

  # GET /curso_escolas/1
  # GET /curso_escolas/1.json
  def show
  end

  # GET /curso_escolas/new
  def new
    @curso_escola = CursoEscola.new
  end

  # GET /curso_escolas/1/edit
  def edit
  end

  # POST /curso_escolas
  # POST /curso_escolas.json
  def create
    @curso_escola = CursoEscola.new(curso_escola_params)

    respond_to do |format|
      if @curso_escola.save
        format.html { redirect_to @curso_escola, notice: 'Curso escola was successfully created.' }
        format.json { render :show, status: :created, location: @curso_escola }
      else
        format.html { render :new }
        format.json { render json: @curso_escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /curso_escolas/1
  # PATCH/PUT /curso_escolas/1.json
  def update
    respond_to do |format|
      if @curso_escola.update(curso_escola_params)
        format.html { redirect_to @curso_escola, notice: 'Curso escola was successfully updated.' }
        format.json { render :show, status: :ok, location: @curso_escola }
      else
        format.html { render :edit }
        format.json { render json: @curso_escola.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /curso_escolas/1
  # DELETE /curso_escolas/1.json
  def destroy
    @curso_escola.destroy
    respond_to do |format|
      format.html { redirect_to curso_escolas_url, notice: 'Curso escola was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso_escola
      @curso_escola = CursoEscola.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_escola_params
      params.require(:curso_escola).permit(:escola_id, :curso_id, :professor_id)
    end
end

app/helpers/curso_escolas_helper.rb
module CursoEscolasHelper
end

app/views/curso_escolas/_form.html.erb
<%= form_for(@curso_escola) do |f| %>
  <% if @curso_escola.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@curso_escola.errors.count, "error") %> prohibited this curso_escola from being saved:</h2>

      <ul>
      <% @curso_escola.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%#= %>

  <div class="field">
    <%= f.label :escola_id %><br>
    <%#= f.text_field :escola_id %>
    <%= f.select(:escola_id, Escola.all.collect {|i| [i.nome, i.id]}, { prompt: "Selecione Escola" })  %>
  </div>
  <div class="field">
    <%= f.label :curso_id %><br>
    <%= f.select(:curso_id, Curso.all.collect {|i| [i.nome, i.id]}, { prompt: "Selecione Escola" })  %>

  </div>
  <div class="field">
    <%= f.label :professor_id %><br>
    <%= f.select(:professor_id, Professor.all.collect {|i| [i.nome, i.id]}, { prompt: "Selecione Escola" })  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/curso_escolas/edit.html.erb
<h1>Editing Curso Escola</h1>

<%= render 'form' %>

<%= link_to 'Show', @curso_escola %> |
<%= link_to 'Back', curso_escolas_path %>

app/views/curso_escolas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Curso Escolas</h1>

<table>
  <thead>
    <tr>
      <th>Escola</th>
      <th>Curso</th>
      <th>Professor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @curso_escolas.each do |curso_escola| %>
      <tr>
        <td><%= curso_escola.escola %></td>
        <td><%= curso_escola.curso %></td>
        <td><%= curso_escola.professor %></td>
        <td><%= link_to 'Show', curso_escola %></td>
        <td><%= link_to 'Edit', edit_curso_escola_path(curso_escola) %></td>
        <td><%= link_to 'Destroy', curso_escola, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Curso escola', new_curso_escola_path %>

app/views/curso_escolas/new.html.erb
<h1>New Curso Escola</h1>

<%= render 'form' %>

<%= link_to 'Back', curso_escolas_path %>

app/views/curso_escolas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Escola:</strong>
  <%= @curso_escola.escola.nome if !@curso_escola.escola.nil? %>
</p>

<p>
  <strong>Curso:</strong>
  <%= @curso_escola.curso.nome  if !@curso_escola.curso.nil?%>
</p>

<p>
  <strong>Professor:</strong>
  <%= @curso_escola.professor.nome if !@curso_escola.professor.nil? %>
</p>

<%= link_to 'Edit', edit_curso_escola_path(@curso_escola) %> |
<%= link_to 'Back', curso_escolas_path %>